export const projectObj = [
  {
    id: "graduate",
    category: "졸업연구",
    title: "가상신호등을 사용한 교통체증 해결안",
    tags: ["python", "SUMO"],
    degree: 100,
  },
  {
    id: "todoApp",
    category: "토이 프로젝트",
    title: "할일을 관리해주는 앱",
    tags: ["react-native", "expo", "firebase"],
    degree: 100,
  },
  {
    id: "jobScrapper",
    category: "토이 프로젝트",
    title: "일자리를 검색해주는 웹사이트",
    tags: ["react", "django", "BeautifulSoup"],
    degree: 100,
  },
  {
    id: "twitter",
    category: "클론코딩",
    title: "트위터 따라하기",
    tags: ["react", "firebase"],
    degree: 100,
  },
  {
    id: "newneek",
    category: "클론코딩",
    title: "NEWNEEK 사이트의 클론코딩",
    tags: ["react", "firebase"],
    degree: 90,
  },
  {
    id: "insta",
    category: "클론코딩",
    title: "인스타그램 클론코딩",
    tags: ["react", "react-native", "graphql", "prisma"],
    degree: 100,
  },
  {
    id: 6,
    category: "클론코딩",
    title: "음음ㅇ므",
    degree: 100,
  },
];
